// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// E1
SEXP E1(SEXP x);
RcppExport SEXP _STLM_E1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(E1(x));
    return rcpp_result_gen;
END_RCPP
}
// E1inv
SEXP E1inv(SEXP y, SEXP epsilon, SEXP Newton);
RcppExport SEXP _STLM_E1inv(SEXP ySEXP, SEXP epsilonSEXP, SEXP NewtonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Newton(NewtonSEXP);
    rcpp_result_gen = Rcpp::wrap(E1inv(y, epsilon, Newton));
    return rcpp_result_gen;
END_RCPP
}
// drawGamma
SEXP drawGamma(SEXP init_elem, SEXP shape, SEXP rate, SEXP epsilon);
RcppExport SEXP _STLM_drawGamma(SEXP init_elemSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type init_elem(init_elemSEXP);
    Rcpp::traits::input_parameter< SEXP >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(drawGamma(init_elem, shape, rate, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// drawGammaRF_1D
SEXP drawGammaRF_1D(SEXP X_, SEXP shape_, SEXP rate_, SEXP epsilon_, SEXP radius_, SEXP type_, SEXP distMatrix_);
RcppExport SEXP _STLM_drawGammaRF_1D(SEXP X_SEXP, SEXP shape_SEXP, SEXP rate_SEXP, SEXP epsilon_SEXP, SEXP radius_SEXP, SEXP type_SEXP, SEXP distMatrix_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type shape_(shape_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type rate_(rate_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type epsilon_(epsilon_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type radius_(radius_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type type_(type_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type distMatrix_(distMatrix_SEXP);
    rcpp_result_gen = Rcpp::wrap(drawGammaRF_1D(X_, shape_, rate_, epsilon_, radius_, type_, distMatrix_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STLM_E1", (DL_FUNC) &_STLM_E1, 1},
    {"_STLM_E1inv", (DL_FUNC) &_STLM_E1inv, 3},
    {"_STLM_drawGamma", (DL_FUNC) &_STLM_drawGamma, 4},
    {"_STLM_drawGammaRF_1D", (DL_FUNC) &_STLM_drawGammaRF_1D, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_STLM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
