# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

E1 <- function(x) {
    .Call('_STLM_E1', PACKAGE = 'STLM', x)
}

E1inv <- function(y, epsilon, Newton) {
    .Call('_STLM_E1inv', PACKAGE = 'STLM', y, epsilon, Newton)
}

drawGamma <- function(init_elem, shape, rate, epsilon) {
    .Call('_STLM_drawGamma', PACKAGE = 'STLM', init_elem, shape, rate, epsilon)
}

drawGammaRF_1D <- function(X_, shape_, rate_, epsilon_, radius_, type_, distMatrix_) {
    .Call('_STLM_drawGammaRF_1D', PACKAGE = 'STLM', X_, shape_, rate_, epsilon_, radius_, type_, distMatrix_)
}

